spawn = require('child_process').spawn
fs    = require 'fs'

sh = (cmd, options) ->
  child = spawn cmd, options
  child.stdout.on 'data', (data) -> process.stdout.write cmd + ':' + data
  child.stderr.on 'data', (data) -> process.stderr.write cmd + ':' + data
  child.on 'error', (data) -> console.log data
  child.on 'close', (code) -> console.log "child #{cmd} closed (#{code})"
  child

task 'server', ->
  server = sh 'coffee', ['server.coffee']
  fs.watch 'server.coffee', ->
    server.kill() if server
    server = sh 'coffee', ['server.coffee']
